[16.0][MIG] pos_default_quantity
coopiteasy/cie-pos pull request #27
Opened 2024-10-14 10:21 UTC by carmenbianca

## Description

Ported, initially proposed to OCA at https://github.com/OCA/pos/pull/1238

## Odoo task (if applicable)

T12149

## Checklist before approval

- [x] Tests are present (or not needed).
- [x] Credits/copyright have been changed correctly.
- [ ] Change log snippet is present.
- [x] (If a new module) Moving this to OCA has been considered.

2024-12-06 09:37 UTC, polchampion requested changes
unsuccessful test on coopcentraal-test
I can see no "default quantity" field on the product category, despite having activated the config

2025-01-29 10:59 UTC, remytms commented
@polchampion It seams that the "Default Quantity" fields is located on the "Unit of Measure Category" and not on "Product Category".

Therefore it appears in the Purchase > Configuration > Units of Measure Categories.
![image](https://github.com/user-attachments/assets/b0b6baaa-ffe9-45b6-a9fa-ab463a3395bb)

2025-02-03 09:55 UTC, polchampion commented
[unsuccessful test on coopcentraal-test](https://coopcentraal.test.coopiteasy.be/pos/ui?config_id=1#cids=1)
--> no default quantity is set for "potatoes" product even though the "weight" unit category's default quantity is set to "10"

@remytms

2025-02-06 15:41 UTC, huguesdk commented
@polchampion for this to work, there are multiple configuration steps needed, as explained [here](https://github.com/coopiteasy/cie-pos/blob/16.0-mig-pos_default_quantity/pos_default_quantity/README.rst#configuration). did you also check the “set default product quantity” checkbox in the point of sale configuration? i tested this in a local database and it seems to work correctly.

2025-02-06 16:12 UTC, polchampion commented
> @polchampion for this to work, there are multiple configuration steps needed, as explained [here](https://github.com/coopiteasy/cie-pos/blob/16.0-mig-pos_default_quantity/pos_default_quantity/README.rst#configuration). did you also check the “set default product quantity” checkbox in the point of sale configuration? i tested this in a local database and it seems to work correctly.

@huguesdk sorry I was too quick

2025-02-06 16:12 UTC, polchampion approved these changes
successful functional test

2025-10-27 14:28 UTC, huguesdk approved these changes

2025-10-27 14:29 UTC, huguesdk commented
/ocabot merge nobump

2025-10-27 14:33 UTC, merged