[ADD] pos_print_receipt_backend
coopiteasy/cie-pos pull request #8
Opened 2020-11-03 10:32 UTC by vvrossem

[Task](https://gestion.coopiteasy.be/web#id=5142&view_type=form&model=project.task&menu_id=338&action=479)

A new module that allows the user to print POS receipts from the Odoo Backend.
The design of the receipt is inspired by the one used for `PosTicket` in `point_of_sale`.

2020-11-04 15:06 UTC, vvrossem commented
closing in favor of [OCA's PR](https://github.com/OCA/web/pull/1723/)

2020-11-04 15:07 UTC, vvrossem commented
oops, wrong PR :D

2020-11-05 09:37 UTC, robinkeunen requested changes
Faudrait passer un petit coup de pre-commit dessus, sinon, les rapports ont l'air bien, pas grand chose à dire :p

2020-11-05 12:40 UTC, vvrossem commented
@robinkeunen `pre-commit run --all-files` effectué.
PS : j'ai mis à jour la description de la PR avec le rendu du ticket, spéciale dédicasse à @remytms

2020-11-09 09:43 UTC, robinkeunen approved these changes

2020-11-09 14:21 UTC, houssine78 commented
@vvrossem you're trolling @remytms with the list of products !

2020-11-09 14:24 UTC, houssine78 commented on pos_print_receipt_backend/views/pos_order_view.xml
> +                <button name="%(action_report_receipt)d" string="Receipt" attrs="{'invisible': [('state', '=', 'draft')]}" type="action" groups="point_of_sale.group_pos_user"/>
a button and an email template to send it by email would be great ! it make it paperless and especially if the customer request the ticket by email and not in the shop.

2020-11-09 14:24 UTC, houssine78 approved these changes

2020-11-09 14:24 UTC, houssine78 commented
@vvrossem  a button and an email template to send it by email would be great ! it make it paperless and especially if the customer request the ticket by email and not in the shop.

2020-11-15 22:00 UTC, remytms commented
@vvrossem Nice troll. XD

2020-11-15 22:00 UTC, merged